"""Build the pronunciation dictionary without a human in the loop.

Two independent automatic checks decide every entry:

  intelligibility — the term is synthesised inside a carrier phrase and read back
                    by ASR; a spelling that comes out as a different word (the
                    «Валдгад» failure) is rejected on string distance.

  stress          — the loudness contour is matched against Silero renderings of
                    the same word with the stress placed on each syllable in turn.
                    That matcher was validated cross-voice at 77% against 25%
                    chance before being used here; a single reading is therefore
                    not trusted, and several seeds vote.

A term that fails either check goes through candidate respellings generated by
rule, and the first candidate passing both is written to the dictionary. Nothing
is decided by ear, and every entry records which check passed and how.
"""
import json, os, re, sys, warnings, subprocess, tempfile
warnings.filterwarnings("ignore"); sys.stdout.reconfigure(encoding="utf-8")
import numpy as np, soundfile as sf

V = "аеёиоуыэюя"
CARRIER = "Здесь важно понять что такое {}."
SEEDS = (1234, 99)


def vowels(w):
    return [i for i, ch in enumerate(w.lower()) if ch in V]


def candidates(say: str):
    """Alternate spellings to try when a term is misheard.

    Doubling a vowel does move the reading, but it also stretches the sound
    audibly, so it is the last resort rather than the first. The earlier options
    are transliteration choices a person would actually make — е against э, one
    consonant against two, a compound written as one word or as two.
    """
    out = [say]
    subs = [("э", "е"), ("е", "э"), ("рр", "р"), ("р", "рр"),
            ("нн", "н"), ("лл", "л"), ("кк", "к"), ("и", "ы")]
    for a, b in subs:
        if a in say.lower():
            i = say.lower().index(a)
            out.append(say[:i] + b + say[i + len(a):])
    if " " in say:
        out.append(say.replace(" ", ""))
        out.append(say.replace(" ", "-"))
    else:
        vp = vowels(say)
        if len(vp) >= 3:
            i = vp[1]
            out.append(say[:i + 1] + " " + say[i + 1:])
    # растяжение гласной — заметно на слух, поэтому в самом конце
    vp = vowels(say)
    for k in (0, 1):
        if k < len(vp):
            i = vp[k]
            out.append(say[:i + 1] + say[i] + say[i + 1:])
    seen, uniq = set(), []
    for c in out:
        if c and c not in seen:
            seen.add(c); uniq.append(c)
    return uniq


DIGITS = {"0": "ноль", "1": "один", "2": "два", "3": "три", "4": "четыре",
          "5": "пять", "6": "шесть", "7": "семь", "8": "восемь", "9": "девять"}


LETTER = {"a":"эй","b":"би","c":"си","d":"ди","e":"и","f":"эф","g":"джи","h":"эйч",
          "i":"ай","j":"джей","k":"кей","l":"эль","m":"эм","n":"эн","o":"о","p":"пи",
          "q":"кью","r":"эр","s":"эс","t":"ти","u":"ю","v":"ви","w":"дабл-ю","x":"экс",
          "y":"уай","z":"зед"}

# аббревиатуры, которые в речи давно стали словами и по буквам не читаются
SPOKEN_AS_WORD = {"JSON":"джейсон","REST":"рест","CAP":"кап","JIT":"джит","FIFO":"фифо",
                  "CAS":"кас","API":"апи","SOAP":"соап","YAML":"ямл","CRUD":"круд",
                  "SQL":"эс-ку-эль","CGLIB":"си-джи-либ","NoSQL":"ноу эс-ку-эль"}


def spell_acronym(term: str) -> str:
    """Побуквенное чтение, выведенное из самого термина.

    Написанное руками «джей-ви-ти» для JWT — это опечатка: W читается «дабл-ю».
    Инструмент такую ошибку подтвердит, потому что проверяет соответствие звука
    написанию, а не написания термину. Поэтому написание выводится правилом.
    """
    if term in SPOKEN_AS_WORD:
        return SPOKEN_AS_WORD[term]
    return "-".join(LETTER.get(ch.lower(), ch) for ch in term if ch.isalpha())


def norm(t):
    """ASR writes numerals as digits — «ТриМэп» comes back as "3Map" — so digits
    are spelled out before comparison, or a correct reading looks like a failure."""
    t = t.lower().replace("ё", "е")
    for d, w in DIGITS.items():
        t = t.replace(d, w)
    return re.sub(r"\s+", " ", re.sub(r"[^а-яa-z ]+", " ", t)).strip()


CYR2LAT = {"а":"a","б":"b","в":"v","г":"g","д":"d","е":"e","ж":"j","з":"z","и":"i",
           "й":"i","к":"k","л":"l","м":"m","н":"n","о":"o","п":"p","р":"r","с":"s",
           "т":"t","у":"u","ф":"f","х":"h","ц":"c","ч":"c","ш":"s","щ":"s","ъ":"",
           "ы":"i","ь":"","э":"e","ю":"u","я":"a"}


def phonetic(t: str) -> str:
    """Reduce both alphabets to one skeleton so «ТриМэп» and "TreeMap" can be compared.

    ASR returns whichever script it recognised the term in, and a transcript often
    mixes the two inside a single word ("триmap"). Comparing raw strings then scores
    a correct reading near zero, which is how this checker rejected 45 good entries
    on its first run.
    """
    t = norm(t)
    t = t.replace("ee", "i").replace("oo", "u").replace("ck", "k").replace("ph", "f")
    out = []
    for ch in t:
        out.append(CYR2LAT.get(ch, ch))
    res = "".join(out)
    res = re.sub(r"(.)+", r"", res)          # схлопываем удвоения: они не различают слова
    return res


def similarity(a, b):
    """Character-level similarity, 0..1, for the intelligibility check."""
    a, b = phonetic(a).replace(" ", ""), phonetic(b).replace(" ", "")
    if not a or not b:
        return 0.0
    from difflib import SequenceMatcher
    return SequenceMatcher(None, a, b).ratio()


def recognised(term: str, say: str, heard: str) -> float:
    """Did the listener hear the intended term?

    ASR writes a term it recognises in its own script: «джей-ви-эм» comes back as
    "JVM", «Спринг Бут» as "Spring Boot". Comparing only against the Cyrillic
    spelling scores those at zero and rejects a perfectly good reading, so the
    English source spelling counts as a match too.
    """
    tail = heard.split("такое")[-1] if "такое" in heard else heard
    return max(similarity(say, tail), similarity(term, tail))


def main():
    sys.path.insert(0, ".")
    from stress_match import build_templates, classify, contour
    import torch
    from qwen_tts import Qwen3TTSModel
    from faster_whisper import WhisperModel

    lex = json.load(open("pronunciation.json", encoding="utf-8"))
    terms = lex["terms"]

    print("загружаю Silero (эталоны ударения) ...", flush=True)
    torch.set_num_threads(12)
    silero = torch.package.PackageImporter("v5_ru.pt").load_pickle("tts_models", "model")

    print("загружаю RUAccent ...", flush=True)
    from onnxruntime import InferenceSession as _I
    _o = _I.run

    def _r(self, n, f, *a, **k):
        mm = {i.name for i in self.get_inputs()} - set(f)
        if mm and "input_ids" in f:
            f = {**f, **{x: np.zeros_like(f["input_ids"]) for x in mm}}
        return _o(self, n, f, *a, **k)

    _I.run = _r
    from ruaccent import RUAccent
    acc = RUAccent(); acc.load(omograph_model_size="turbo3.1", use_dictionary=True, tiny_mode=False)

    print("загружаю Qwen3-TTS ...", flush=True)
    qwen = Qwen3TTSModel.from_pretrained("Qwen/Qwen3-TTS-12Hz-1.7B-Base",
                                         device_map="cuda:0", dtype=torch.bfloat16)
    print("загружаю Whisper ...", flush=True)
    asr = WhisperModel("large-v3-turbo", device="cuda", compute_type="float16")

    rt = json.load(open("lv/ref_texts.json", encoding="utf-8"))
    ref_text = next(v for k, v in rt.items() if "ref_t2" in k)
    REF = "lv/ref_t2.wav"
    os.makedirs("autolex", exist_ok=True)

    def is_acronym(term: str) -> bool:
        """Аббревиатуры читаются побуквенно, ударение в них не определено —
        мнение акцентуатора о такой «словоформе» бессмысленно."""
        return term.isupper() and len(term) <= 5

    def expected_stress(word):
        m = acc.process_all(word)
        vs, hit, idx = 0, False, None
        for ch in m:
            if ch == "+":
                hit = True; continue
            if ch.lower() in V:
                if hit:
                    idx = vs; hit = False
                vs += 1
        return idx, vs

    def render(text, seed):
        torch.manual_seed(seed)
        w, sr = qwen.generate_voice_clone(text=text, language="Russian",
                                          ref_audio=REF, ref_text=ref_text)
        return np.asarray(w[0], dtype=np.float32), sr

    def hear(x, sr):
        with tempfile.TemporaryDirectory() as d:
            p = os.path.join(d, "a.wav"); sf.write(p, x, sr)
            segs, _ = asr.transcribe(p, language="ru", beam_size=5)
            return " ".join(s.text for s in segs).strip()

    results, fixed, flagged = [], 0, 0
    items = list(terms.items())
    for n, (term, meta) in enumerate(items, 1):
        say = meta["say"]
        head = say.split()[0] if " " in say else say
        exp, nv = expected_stress(head)
        skip_stress = is_acronym(term)
        tpl = {} if skip_stress else (build_templates(silero, head, "eugene")
                                      if (exp is not None and nv >= 2) else {})

        chosen, log = None, []
        for cand in candidates(say):
            x, sr = render(CARRIER.format(cand), SEEDS[0])
            heard = hear(x, sr)
            sim = recognised(term, cand, heard)
            votes = []
            for sd in (SEEDS if tpl else ()):
                xa, ss = render(head + ".", sd)
                g = classify(contour(xa, ss), tpl)
                if g is not None:
                    votes.append(g)
            got = max(set(votes), key=votes.count) if votes else None
            ok_sound = sim >= 0.62
            ok_stress = (exp is None or got is None or got == exp)
            log.append({"cand": cand, "heard": heard, "sim": round(sim, 2),
                        "stress_expected": exp, "stress_detected": got,
                        "ok_sound": ok_sound, "ok_stress": ok_stress})
            if ok_sound and ok_stress:
                chosen = cand
                sf.write(f"autolex/{re.sub(r'[^A-Za-z0-9]', '_', term)}.wav", x, sr)
                break

        status = "ok" if chosen == say else ("fixed" if chosen else "unresolved")
        if status == "fixed":
            fixed += 1
        if status == "unresolved":
            flagged += 1
        results.append({"term": term, "proposed": say, "chosen": chosen,
                        "status": status, "tries": log})
        mark = {"ok": "  ", "fixed": " ~", "unresolved": " !"}[status]
        print(f"{mark} [{n:2}/{len(items)}] {term:20} → {chosen or '—':22} {status}", flush=True)

    ok = sum(1 for r in results if r["status"] == "ok")
    print(f"\nпринято как есть {ok}, исправлено {fixed}, не решено {flagged}")
    json.dump(results, open("results_autolex.json", "w", encoding="utf-8"),
              ensure_ascii=False, indent=1)

    for r in results:
        e = terms[r["term"]]
        e["say"] = r["chosen"] or e["say"]
        e["verified"] = r["status"] in ("ok", "fixed")
        e["check"] = r["status"]
    lex["note"] = ("Собран автоматически: разборчивость проверена обратным распознаванием, "
                   "ударение — сопоставлением контура с эталонами Silero (валидация метода 77% "
                   "при 25% случайного). Человек в цикле не участвует.")
    json.dump(lex, open("pronunciation.json", "w", encoding="utf-8"), ensure_ascii=False, indent=2)


if __name__ == "__main__":
    main()
